name: Pull Request Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
      
      - name: Install application
        run: |
          pip install ".[dev]"
          pip install pytest-timeout

      - name: Create credentials.json
        run: >
          echo
          '{"github-credentials":[
          {"repository":"https://github.com/sec-digital-twin-lab/duct-fom",
          "login":"oauth",
          "personal_access_token":"${{ secrets.TEST_PROCESSOR_KEY }}"}
          ]}' > ~/.saas-credentials.json

      - name: Run tests
        run: pytest -v --timeout=300 ./tests

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          # ignore line too long errors
          args: --ignore E501
